### ISSUE TITLE
log-transformed values in Quantile RF

### ISSUE THREAD

**Issue by viatkin** [FAO-GSP/SOC-Mapping-Cookbook#13]
Chapter 12 code for Quantile Regression Forest uses column OCSKGMlog instead of OCSKGM. This column is created in Chapter 4, but never in Chapter 12, therefore the code in Chapter 12 doesn't work. We need either to change the code in Chapter 12 QuantileRF (e.g. by using log(OCSKGM) instead of OCSKGMlog), or add the creation of OCSKGMlog column to Chapter 12 data preparation scripts.

**Comment by midraed** [comment]
it should be log(OCSKGM) everywhere. We don't need to create a new variable only for this.
