### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by viatkin** [FAO-GSP/SOC-Mapping-Cookbook#14]
1. Validation code in Chapter 12 is only for Random Forest which is not interesting. I think it would be better to copy there the codes from Chapter 7.5

2. In Chapter 7.5 the code 
_dat <- extract(x = OCSKGM_RK, y = dat, sp = TRUE)_  will not work, because raster OCSKGM_RK is in metric coordinate system with which it was created in Chapter 6. We either need to reproject it in Chapter 7 before extracting values, or in Chapter 6 before writing a .tiff file.

3. In Chapter 7.5. the formulas for amount of variance explained are wrong. E.g.:
_AVE_GM <- 1 - sum(dat$PE_GM^2, na.rm=TRUE) / 
  sum( (**dat$MKD_OCSKGM_GM** - mean(dat$OCSKGM, na.rm = TRUE))^2, 
       na.rm = TRUE)_
should be:
_AVE_GM <- 1 - sum(dat$PE_GM^2, na.rm=TRUE) / 
  sum( (**dat$OCSKGM** - mean(dat$OCSKGM, na.rm = TRUE))^2, 
       na.rm = TRUE)_
Same error also for AVE_RK, AVE_rf, AVE_svm

**Comment by midraed** [comment]
2018-04-10 15:23 GMT+02:00 viatkin <notifications@github.com>:

>
>    1.
>
>    Validation code in Chapter 12 is only for Random Forest which is not
>    interesting. I think it would be better to copy there the codes from
>    Chapter 7.5O
>
>
No. Is an example. Is the code needed to validate any model. We are using
rf as an example, but it could be any model. we are providing an example of
the code needed not validating all the models like in 7.5.


>
>    1.
>
>    In Chapter 7.5 the code
>    *dat <- extract(x = OCSKGM_RK, y = dat, sp = TRUE)* will not work,
>    because raster OCSKGM_RK is in metric coordinate system with which it was
>    created in Chapter 6. We either need to reproject it in Chapter 7 before
>    extracting values, or in Chapter 6 before writing a .tiff file.
>
>
The code IS working. Remember, the table 7.2 for example, doesnt exists if
the code doesn't work. Everytime we compile the book, that chunk of code
and every other chunk runs, and produce a result. And those results
populate the figures and tables of the book. So, the code is working. If
you try manually, when you run extract() you will have a warning related to
the different CRS. But sp package will transform the data before running
the extraction.

>
>    1.
>    2.
>
>    In Chapter 7.5. the formulas for amount of variance explained are
>    wrong. E.g.:
>
>
> *AVE_GM <- 1 - sum(dat$PE_GM^2, na.rm=TRUE) / sum( (dat$MKD_OCSKGM_GM -
>    mean(dat$OCSKGM, na.rm = TRUE))^2, na.rm = TRUE)*
>    should be:
>
>
> *AVE_GM <- 1 - sum(dat$PE_GM^2, na.rm=TRUE) / sum( (dat$OCSKGM -
>    mean(dat$OCSKGM, na.rm = TRUE))^2, na.rm = TRUE)*
>    Same error also for AVE_RK, AVE_rf, AVE_svm
>
>
You are right! My fault.
