### ISSUE TITLE
missing spline figure in chapter 4

### ISSUE THREAD

**Issue by midraed** [FAO-GSP/SOC-Mapping-Cookbook#4]
was there on 1st edition!

**Comment by yigini** [comment]
*---------------*

*Yusuf Yigini* | *Global Soil Partnership (GSP)* | * Pillar 4 Coordination*
 | *Food and Agriculture Organization of the United Nations (FAO*) | Land
and Water Division (CBL)| Viale delle Terme di Caracalla, I-00153 Rome,
Room B-708Bis | Office: 0039-06-570-53772 Mobile: 0039-366-3021382
<366%20302%201382> | ​yusuf.yigini@fao.org
www.fao.org/global-soil-partnership/en/ | ​GSOCMap Technical Support:
GSP-GSOC-Map@fao.org

**Comment by viatkin** [comment]
added figure from the 1st edition
