### ISSUE TITLE
broken reference in chapter 2 

### ISSUE THREAD

**Issue by viatkin** [FAO-GSP/SOC-Mapping-Cookbook#6]
\index{Soil Information System (SIS)!global} - not working

**Comment by midraed** [comment]
Kostya, we decided to remove the index. The index is the one in the back in
alphabetical order, not the table of contents.

2018-04-06 8:25 GMT-03:00 viatkin <notifications@github.com>:

**Comment by viatkin** [comment]
Okay, shall I remove that piece of code then? Because it creates a space before a comma - that's how I noticed something was wrong...

**Comment by midraed** [comment]
yes, they should be ignored, but if you need you can remove them. It was a
feature to create an index for the pdf version, but we didn't have time to
complete it.




2018-04-06 9:03 GMT-03:00 viatkin <notifications@github.com>:

**Comment by viatkin** [comment]
ok, I kept them, but removed excess spaces before them
